# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file: database.env
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"